"""Configuration constants for the Linked Data Explorer."""

from rdflib import Namespace, URIRef
from rdflib.namespace import RDFS

CONFIG = {
    "NAMESPACE": "http://example.org/",
    "RELATIONSHIP_CONFIG": {
        "relatedPerson": "#E07A5F",
        "influencedBy": "#E9C46A",
        "memberOf": "#3D5A80",
        "succeededBy": "#B56576",
        "precededBy": "#6D597A",
        "relatedOrganization": "#457B9D",
        "headquarters": "#2A9D8F",
        "administrativelyPartOf": "#4D8DA8",
        "placeOfBirth": "#81B29A",
        "placeOfDeath": "#6C8F6B",
        "residence": "#A7C5BD",
        "draftsman": "#C76D4B",
        "depicts": "#F4A261",
        "relatedWork": "#70B7B2",
        "conservationAction": "#C98F52",
        "performedBy": "#4F6D7A",
        "creator": "#E07A5F",
        "author": "#355070",
        "contributor": "#7AA4C1",
        "associatedWith": "#9A8F5C",
        "sameAs": "#5C5F66",
        "child": "#F7B2A0",
        "sibling": "#F2D388",
        "spouse": "#B56576",
        "studentOf": "#F4A261",
        "employedBy": "#2A9D8F",
        "occupation": "#84A59D",
        "fieldOfActivity": "#E9C46A",
        "educatedAt": "#4D8DA8",
        "foundedBy": "#C76D4B",
        "containedInPlace": "#6C8F6B",
        "owner": "#3D5A80",
        "isPartOf": "#457B9D",
        "hasPart": "#8D99AE",
        "relatedPlace": "#A7C5BD",
        "analysisOf": "#6D597A",
        "dedicatee": "#F7B2A0",
        "illustrator": "#E07A5F",
        "artist": "#B56576",
        "editor": "#9A8F5C",
        "designer": "#F4A261",
        "composer": "#9C6644",
        "translator": "#7AA4C1",
        "inspiredBy": "#E9C46A",
    },
    "NODE_TYPE_COLORS": {
        "Person": "#E07A5F",
        "Organization": "#3D5A80",
        "Place": "#81B29A",
        "StillImage": "#F2CC8F",
        "Event": "#B56576",
        "Work": "#4D8DA8",
        "Music": "#2A9D8F",
        "AdministrativeArea": "#A7C5BD",
        "ConservationAction": "#C98F52",
        "Unknown": "#C9C6BE",
    },
    "NODE_TYPE_SHAPES": {
        "Person": "circle",
        "Organization": "box",
        "Place": "triangle",
        "StillImage": "dot",
        "Event": "star",
        "Work": "ellipse",
        "Music": "triangleDown",
        "AdministrativeArea": "diamond",
        "ConservationAction": "diamond",
        "Unknown": "dot",
    },
    "NODE_TYPE_ICONS": {
        "Person": "P",
        "Organization": "O",
        "Place": "L",
        "StillImage": "I",
        "Event": "E",
        "Work": "W",
        "Music": "M",
        "AdministrativeArea": "A",
        "ConservationAction": "C",
        "Unknown": "?",
    },
    "DEFAULT_NODE_COLOR": "#C9C6BE",
    "GRAPH_BACKGROUND": {
        "radial_1": "#E07A5F",
        "radial_2": "#2A9D8F",
        "linear_1": "#FCFAF6",
        "linear_2": "#F4EFE6",
    },
    "COMMUNITY_COLORS": [
        "#3D5A80",
        "#E07A5F",
        "#2A9D8F",
        "#F4A261",
        "#6D597A",
        "#84A59D",
        "#F2D388",
        "#B56576",
        "#7AA4C1",
        "#5C5F66",
    ],
    "PHYSICS_DEFAULTS": {
        "gravity": -50,
        "centralGravity": 0.01,
        "springLength": 150,
        "springStrength": 0.08,
    },
}

EX = Namespace(CONFIG["NAMESPACE"])
ASSERTED_CTX = URIRef("http://example.org/asserted")
INFERRED_CTX = URIRef("http://example.org/inferred")

APP_FONTS = {
    "display": "Fraunces",
    "body": "IBM Plex Sans",
    "mono": "IBM Plex Mono",
}
VIS_FONT_FACE = "\"IBM Plex Sans\", \"Helvetica Neue\", Arial, sans-serif"
GRAPH_CANVAS_HEIGHT = 800
GRAPH_PANEL_PADDING = 12
GRAPH_PANEL_BORDER = 1
GRAPH_CARD_HEIGHT = GRAPH_CANVAS_HEIGHT + 2 * (GRAPH_PANEL_PADDING + GRAPH_PANEL_BORDER)
MAX_RENDER_NODES = 500

TYPE_SYNONYMS = {
    "Agent": "Person",
    "Human": "Person",
    "Actor": "Person",
    "Agentive": "Person",
    "Image": "StillImage",
    "Photograph": "StillImage",
    "ImageObject": "StillImage",
    "VisualArtwork": "Work",
    "CreativeWork": "Work",
    "Book": "Work",
    "Article": "Work",
    "Manuscript": "Work",
    "Document": "Work",
    "Text": "Work",
    "MusicComposition": "Music",
    "MusicRecording": "Music",
    "MusicAlbum": "Music",
    "MusicGroup": "Organization",
    "PerformingGroup": "Organization",
    "Organization": "Organization",
    "Group": "Organization",
    "Corporation": "Organization",
    "LocalBusiness": "Organization",
    "EducationalOrganization": "Organization",
    "GovernmentOrganization": "Organization",
    "Place": "Place",
    "SpatialThing": "Place",
    "Location": "Place",
    "AdministrativeArea": "AdministrativeArea",
    "Event": "Event",
    "HistoricalEvent": "Event",
    "Person": "Person",
    "Work": "Work",
    "Music": "Music",
    "StillImage": "StillImage",
    "E21_Person": "Person",
    "E39_Actor": "Person",
    "E74_Group": "Organization",
    "E40_Legal_Body": "Organization",
    "E53_Place": "Place",
    "E5_Event": "Event",
    "E28_Conceptual_Object": "Work",
    "E22_Man-Made_Object": "Work",
    "E24_Physical_Man-Made_Thing": "Work",
    "E31_Document": "Work",
    "ConservationAction": "ConservationAction",
}

NAMESPACE_PREFIXES = {
    "http://schema.org/": "schema",
    "https://schema.org/": "schema",
    "http://xmlns.com/foaf/0.1/": "foaf",
    "http://www.cidoc-crm.org/cidoc-crm/": "crm",
    "http://www.w3.org/2004/02/skos/core#": "skos",
    "http://www.w3.org/2000/01/rdf-schema#": "rdfs",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#": "rdf",
    "http://www.w3.org/2002/07/owl#": "owl",
    "http://vocab.getty.edu/ulan/relationships/": "ulan-rel",
    "https://vocab.getty.edu/ulan/relationships/": "ulan-rel",
    "http://vocab.getty.edu/ulan/": "ulan",
    "https://vocab.getty.edu/ulan/": "ulan",
    "http://vocab.getty.edu/page/ulan/": "ulan",
    "https://vocab.getty.edu/page/ulan/": "ulan",
    "http://vocab.getty.edu/tgn/": "tgn",
    "https://vocab.getty.edu/tgn/": "tgn",
    "http://vocab.getty.edu/page/tgn/": "tgn",
    "https://vocab.getty.edu/page/tgn/": "tgn",
    "http://vocab.getty.edu/aat/": "aat",
    "https://vocab.getty.edu/aat/": "aat",
    "http://vocab.getty.edu/page/aat/": "aat",
    "https://vocab.getty.edu/page/aat/": "aat",
    "http://vocab.getty.edu/language/": "lang",
    "https://vocab.getty.edu/language/": "lang",
    "http://vocab.getty.edu/page/language/": "lang",
    "https://vocab.getty.edu/page/language/": "lang",
    "https://id.oclc.org/worldcat/entity/": "oclc",
    "http://id.oclc.org/worldcat/entity/": "oclc",
    "https://id.worldcat.org/fast/": "fast",
    "http://id.loc.gov/vocabulary/languages/": "loc-lang",
    "https://www.wikidata.org/wiki/": "wd",
    "https://linked.art/ns/v1/": "linkedart",
}

RDFS_PREDICATE_SUFFIXES = {
    "subclassof": RDFS.subClassOf,
    "subpropertyof": RDFS.subPropertyOf,
    "domain": RDFS.domain,
    "range": RDFS.range,
    "seealso": RDFS.seeAlso,
    "isdefinedby": RDFS.isDefinedBy,
}
